<?php
//https://www.musixmatch.com/pt-br
$musicas = [
	//Racionais
	['artista' => 'Racionais', 'id' => '7l-tp7yyJaE', 'title' => '1 por Amor 2 por Dinheiro'], //Música inicial
	['artista' => 'Racionais', 'id' => 'b-_nIr_AOyo', 'title' => 'A vítima'],
	['artista' => 'Racionais', 'id' => 'TITRneC6jLU', 'title' => 'Capítulo 4 Versículo 3'],
	['artista' => 'Racionais', 'id' => 'J9V9yackzzo', 'title' => 'Crime vai e vem'],
	['artista' => 'Racionais', 'id' => 'HlHN8VSIRwE', 'title' => 'Da ponte pra cá'],
	['artista' => 'Racionais', 'id' => 'dGFxdmuDA4A', 'title' => 'Diário de um Detento'],
	['artista' => 'Racionais', 'id' => 'fgysUhl98As', 'title' => 'Eu sou 157'],
	['artista' => 'Racionais', 'id' => '27c_CPWdARU', 'title' => 'Expresso da meia noite'],
	['artista' => 'Racionais', 'id' => '9nUHk06-bX4', 'title' => 'Fórmula Mágica da Paz'],
	['artista' => 'Racionais', 'id' => 'oSxnR7cERpI', 'title' => 'Fim de semana no parque'],
	['artista' => 'Racionais', 'id' => 'SkHS9r1haXE', 'title' => 'Homem na Estrada'],
	['artista' => 'Racionais', 'id' => 'Hqp_LkLzFFM', 'title' => 'Jesus Chorou'],
	['artista' => 'Racionais', 'id' => 'mrAT_xG-opk', 'title' => 'Negro Drama'],
	['artista' => 'Racionais', 'id' => 'txSXj-F7VX8', 'title' => 'Tô ouvindo alguém me chamar'],
	['artista' => 'Racionais', 'id' => '1Q7xbzQK5YA', 'title' => 'Vida Loka Parte I'],
	['artista' => 'Racionais', 'id' => 'Qv9ayypY1dQ', 'title' => 'Vida Loka Parte II'],
	['artista' => 'Racionais', 'id' => '4PNmrGkiXUE', 'title' => 'A vida é desafio'],

	//Charlie Brown Jr - parte 1 Chegou Quem Faltava
	['artista' => 'Charlie Brown Jr - 1', 'category' => " - Chegou Quem Faltava", 'id' => 'ulO5opUXnBk', 'title' => 'Pontes Indestrutíveis (Ao Vivo - Chegou Quem Faltava)'],
	['artista' => 'Charlie Brown Jr - 1', 'category' => " - Chegou Quem Faltava", 'id' => '423K3pipX3c', 'title' => 'Dias de Luta, Dias de Glória (Ao Vivo - Chegou Quem Faltava)'],
	['artista' => 'Charlie Brown Jr - 1', 'category' => " - Chegou Quem Faltava", 'id' => 'ZXtfbLYQbWE', 'title' => 'Zóio de Lula (Ao Vivo - Chegou Quem Faltava)'],
	['artista' => 'Charlie Brown Jr - 1', 'category' => " - Chegou Quem Faltava", 'id' => 'NFADwNLNSd4', 'title' => 'Só os Loucos Sabem (Ao Vivo - Chegou Quem Faltava)'],
	['artista' => 'Charlie Brown Jr - 1', 'category' => " - Chegou Quem Faltava", 'id' => '7Et5fkuzxdQ', 'title' => 'Confisco (Ao Vivo - Chegou Quem Faltava)'],
	['artista' => 'Charlie Brown Jr - 1', 'category' => " - Chegou Quem Faltava", 'id' => 'h8J1zXi2FoI', 'title' => 'Não é Sério (Ao Vivo - Chegou Quem Faltava)'],
	['artista' => 'Charlie Brown Jr - 1', 'category' => " - Chegou Quem Faltava", 'id' => 'liUFyz_sXLE', 'title' => 'Proibida pra Mim (Grazon) (Ao Vivo - Chegou Quem Faltava)'],
	['artista' => 'Charlie Brown Jr - 1', 'category' => " - Chegou Quem Faltava", 'id' => 'PeloX9xnOlQ', 'title' => 'Longe de Você (Ao Vivo - Chegou Quem Faltava)'],
	['artista' => 'Charlie Brown Jr - 1', 'category' => " - Chegou Quem Faltava", 'id' => 't63QK7yO2bA', 'title' => 'Tudo Mudar (Ao Vivo - Chegou Quem Faltava)'],
	['artista' => 'Charlie Brown Jr - 1', 'category' => " - Chegou Quem Faltava", 'id' => 'UPWmNXxokJc', 'title' => 'Rubão, o Dono do Mundo (Ao Vivo - Chegou Quem Faltava)'],
	['artista' => 'Charlie Brown Jr - 1', 'category' => " - Chegou Quem Faltava", 'id' => 'DzhwydXmtH4', 'title' => 'Céu Azul (Ao Vivo - Chegou Quem Faltava)'],
	['artista' => 'Charlie Brown Jr - 1', 'category' => " - Chegou Quem Faltava", 'id' => 'qsqZ_3panF0', 'title' => 'Eu Vim de Santos, Sou Charlie Brown (Ao Vivo - Chegou Quem Faltava)'],
	['artista' => 'Charlie Brown Jr - 1', 'category' => " - Chegou Quem Faltava", 'id' => 'dlMs7c2GSps', 'title' => 'Papo Reto (Prazer é Sexo, o Resto é Negócio) (Ao Vivo - Chegou Quem Faltava)'],
	['artista' => 'Charlie Brown Jr - 1', 'category' => " - Chegou Quem Faltava", 'id' => 'NRKBDBxywZk', 'title' => 'Three Little Birds (Ao Vivo - Chegou Quem Faltava)'],
	['artista' => 'Charlie Brown Jr - 1', 'category' => " - Chegou Quem Faltava", 'id' => 'AktA7DH9LOc', 'title' => 'Ela Vai Voltar (Manhãs de Setembro) (Ao Vivo - Chegou Quem Faltava)'],
	['artista' => 'Charlie Brown Jr - 1', 'category' => " - Chegou Quem Faltava", 'id' => 'zr5X-40_Ntc', 'title' => 'O Preço (Ao Vivo - Chegou Quem Faltava)'],
	['artista' => 'Charlie Brown Jr - 1', 'category' => " - Chegou Quem Faltava", 'id' => 'vMMrM6XH0HM', 'title' => 'Senhor do Tempo (Ao Vivo - Chegou Quem Faltava)'],
	['artista' => 'Charlie Brown Jr - 1', 'category' => " - Chegou Quem Faltava", 'id' => 'BANcODKDabY', 'title' => 'Mantenha a Dúvida e Espere Até Ouvir Falar de Nós (Ao Vivo - Chegou Quem Faltava)'],
	['artista' => 'Charlie Brown Jr - 1', 'category' => " - Chegou Quem Faltava", 'id' => 'iPeGxRsrh9s', 'title' => 'Cheia de Vida (Ao Vivo - Chegou Quem Faltava)'],
	['artista' => 'Charlie Brown Jr - 1', 'category' => " - Chegou Quem Faltava", 'id' => 'xwXdlssfwbI', 'title' => 'Tudo Que Ela Gosta de Escutar (Ao Vivo - Chegou Quem Faltava)'],
	['artista' => 'Charlie Brown Jr - 1', 'category' => " - Chegou Quem Faltava", 'id' => 'F-p9VY5gGZM', 'title' => 'Me Encontra (Ao Vivo - Chegou Quem Faltava)'],
	['artista' => 'Charlie Brown Jr - 1', 'category' => " - Chegou Quem Faltava", 'id' => 'P0HJZsp0ImE', 'title' => 'O Côro Vai Comê (Ao Vivo - Chegou Quem Faltava)'],
	['artista' => 'Charlie Brown Jr - 1', 'category' => " - Chegou Quem Faltava", 'id' => 'aUMh6uFiurk', 'title' => 'Di Sk8 Eu Vou (Ao Vivo - Chegou Quem Faltava)'],
	['artista' => 'Charlie Brown Jr - 1', 'category' => " - Chegou Quem Faltava", 'id' => 'XK9wZ_6UPFg', 'title' => 'Te Levar Daqui (Ao Vivo - Chegou Quem Faltava)'],
	['artista' => 'Charlie Brown Jr - 1', 'category' => " - Chegou Quem Faltava", 'id' => 'OWla_t1KdOI', 'title' => 'Rock Star (Ao Vivo - Chegou Quem Faltava)'],
	['artista' => 'Charlie Brown Jr - 1', 'category' => " - Chegou Quem Faltava", 'id' => '9R6Aw01F7V0', 'title' => 'Quinta-Feira (Ao Vivo - Chegou Quem Faltava)'],
	['artista' => 'Charlie Brown Jr - 1', 'category' => " - Chegou Quem Faltava", 'id' => 'umG3fmb2LbY', 'title' => 'Gimme o Anel / Sheik (Ao Vivo - Chegou Quem Faltava)'],
	['artista' => 'Charlie Brown Jr - 1', 'category' => " - Chegou Quem Faltava", 'id' => 'GRfud4teZlA', 'title' => 'Charlie Brown Jr. - Charlie Brown Jr. (Ao Vivo - Chegou Quem Faltava)'],


	//Charlie Brown Jr
	['artista' => 'Charlie Brown Jr', 'id' => '4vibeaN0BG0', 'title' => 'Rubao'],
	['artista' => 'Charlie Brown Jr', 'id' => 'tZqRfuGpUOA', 'title' => 'Papo Reto'],
	['artista' => 'Charlie Brown Jr', 'id' => 'w_HUCmMnB5o', 'title' => 'Não É Sério'],
	['artista' => 'Charlie Brown Jr', 'id' => 'KgAZWXqK7Ac', 'title' => 'Ela Vai Voltar'],
	['artista' => 'Charlie Brown Jr', 'id' => 'bZTwKUJDU1M', 'title' => 'Pontes Indestrutíveis'],
	['artista' => 'Charlie Brown Jr', 'id' => 'TJRIZS4Z7Mw', 'title' => 'Proibida Pra Mim'],
	['artista' => 'Charlie Brown Jr', 'id' => '2RobhjC7cR4', 'title' => 'Não Deixe O Mar Te Engolir'],
	['artista' => 'Charlie Brown Jr', 'id' => 'oXBWG4owmvE', 'title' => 'Só Por Uma Noite'],
	['artista' => 'Charlie Brown Jr', 'id' => 'GDmo1WEBUSw', 'title' => 'Vivendo Nesse Absurdo'],
	['artista' => 'Charlie Brown Jr', 'id' => 'uJmV3W_xcd0', 'title' => 'Onde Esta O Mundo Bom?'],
	['artista' => 'Charlie Brown Jr', 'id' => '5FZ76ztmrkY', 'title' => 'Vicios E Virtudes'],
	['artista' => 'Charlie Brown Jr', 'id' => 'HSOSaCzTtoU', 'title' => 'Tamo Ai Na Atividade'],
	['artista' => 'Charlie Brown Jr', 'id' => '_o9J0BXiZXI', 'title' => 'Skate Vibration'],
	['artista' => 'Charlie Brown Jr', 'id' => 'CpmopU2Tvkw', 'title' => 'T.F.D.P.'],
	['artista' => 'Charlie Brown Jr', 'id' => 'CQbJWlj5ykU', 'title' => 'Onde Não Existe A Paz Não Existe O Amor'],
	['artista' => 'Charlie Brown Jr', 'id' => 'wM8Zwz2N7YY', 'title' => 'Pra Não Dizer Que Não Falei Das Flores'],
	['artista' => 'Charlie Brown Jr', 'id' => 'gWa4b35AeIw', 'title' => 'Lutar Pelo Que É Meu'],
	['artista' => 'Charlie Brown Jr', 'id' => 'EEj_YaXZ3xU', 'title' => 'Senhor Do Tempo'],
	['artista' => 'Charlie Brown Jr', 'id' => 'wVfiBTF5CHo', 'title' => 'Beco Sem Saída'],
	['artista' => 'Charlie Brown Jr', 'id' => 'vF_SYOd1_z0', 'title' => 'Tudo Que Ela Gosta De Escutar (Extra)'],
	['artista' => 'Charlie Brown Jr', 'id' => 'SttHLiINvCw', 'title' => 'Zoio De Lula (Extra)'],
	['artista' => 'Charlie Brown Jr', 'id' => 'JRJj4z-prvM', 'title' => 'Só os Loucos Sabem (Video Clipe)'],
	['artista' => 'Charlie Brown Jr', 'id' => 'yQvb-B7g0ng', 'title' => 'Homenagem ao Santos Futebol Clube'],
	['artista' => 'Charlie Brown Jr', 'id' => 'bcLo0lBRwwE', 'title' => 'Dona do Meu Pensamento (webclipe)'],
	['artista' => 'Charlie Brown Jr', 'id' => 'Qv6IZkh4fFM', 'title' => 'Me encontra (Video Clipe)'],
	['artista' => 'Charlie Brown Jr', 'id' => 'GzqBwUA3wJw', 'title' => 'Um Dia A Gente Se Encontra'],
	['artista' => 'Charlie Brown Jr', 'id' => 'spwnIS4WdxI', 'title' => 'Puro Sangue'],
	['artista' => 'Charlie Brown Jr', 'id' => 'WidXbFRpNaU', 'title' => 'Só Pra Vadiar'],
	['artista' => 'Charlie Brown Jr', 'id' => 'i7JeqZ1gcis', 'title' => 'Dias De Luta, Dias De Glória'],
	['artista' => 'Charlie Brown Jr', 'id' => 'DzhwydXmtH4', 'title' => 'Céu Azul (Ao Vivo - Chegou Quem Faltava)'],
	// ['id' => '', 'title' => ''],
	// ['id' => '', 'title' => ''],
	// ['id' => '', 'title' => ''],

	//Charlie Brown Jr. e Vanessa da Mata
	['artista' => 'Charlie Brown Jr', 'id' => 'o2kuUUZ-0o8', 'title' => 'Ai Ai Ai'],
	['artista' => 'Vanessa da Mata', 'id' => 'i4OMvyz5GVg', 'title' => 'Lutar Pelo Que É Meu (versão Estúdio Coca Cola Zero)'],
	['artista' => 'Vanessa da Mata', 'id' => 'QF2hrEAgvPY', 'title' => 'Pontes Indestrutiveis (versão Estúdio Coca-Cola Zero)'],
	['artista' => 'Charlie Brown Jr', 'id' => 'm5SB3bstyK0', 'title' => 'Senhor do Tempo / Não Me Deixe Só'],
	['artista' => 'Vanessa da Mata', 'id' => 'orDuyh29Qsc', 'title' => 'O Que Ela Gosta É de Barriga (versão Estúdio Coca-Cola Zero)'],
	['artista' => 'Vanessa da Mata', 'id' => '2ruGju6yrko', 'title' => 'Não Me Deixe Só'],
	// ['id' => '', 'title' => ''],
	// ['id' => '', 'title' => ''],


	//Facção central
	// ['id'=>'BSThdXGDDXc', 'title' => 'Eu Não Pedi pra Nascer'],
	// ['id' => 'HyJFBE-VGf0','title' => 'Estrada da Dor 666'],
	// ['id' => 'jtkM5MNnHV8','title' => 'Desculpa Mãe'],

	//Ao Cubo
	['artista' => 'Ao Cubo', 'id' => 'UbxlxjU9Sak', 'title' => 'Cicatrizes ft. Irmão Lázaro'],
	['artista' => 'Ao Cubo', 'id' => '1BUqFs6H1L8', 'title' => 'Cinderela'],
	['artista' => 'Ao Cubo', 'id' => 'CMdOKTvq8E0', 'title' => 'Filhos (Versão Oficial)'],
	['artista' => 'Ao Cubo', 'id' => 'OAMbVlhdrlo', 'title' => 'Mil Desculpas'],
	['artista' => 'Ao Cubo', 'id' => 'njs2hhSsRa4', 'title' => 'Naquela Sala'],

	//	
	['artista' => 'Mc Ryan Sp', 'id' => '5LqeD-m7Iho', 'title' => 'ILUSÃO "CRACOLÂNDIA"'],

	//Tauz
	['artista' => 'PlayerTauz', 'id' => '-m9kWTgze4Y', 'title' => 'Rap do Minato (Naruto) | Tauz RapTributo 24 (Original)'],
	['artista' => 'PlayerTauz', 'id' => 'Xx0Q9IaoU8k', 'title' => 'Rap do Shisui (Naruto) - Tauz RapTributo 54'],
	['artista' => 'PlayerTauz', 'id' => 'boG-ElwL6Fg', 'title' => 'Rap do Naruto (Remake) | Tauz RapTributo 73 (Editado)'],
	['artista' => 'PlayerTauz', 'id' => 'bAmy7oyn0UI', 'title' => 'Rap do Bardock (Dragon Ball Z) | Tauz RapTributo 22'],
	['artista' => 'PlayerTauz', 'id' => 'ixrqpQidpb8', 'title' => 'Rap do Vegeta (Dragon Ball Z) | Tauz RapTributo 04'],
	['artista' => 'PlayerTauz', 'id' => 'bxoQmntckXU', 'title' => 'Rap do Shikamaru (Naruto) | Tauz RapTributo 08'],
	['artista' => 'PlayerTauz', 'id' => 'x7QLDSzK8jw', 'title' => 'Rap do Hitto (Dragon Ball Super) | Tauz RapTributo 10'],
	['artista' => 'PlayerTauz', 'id' => 'JY66s8blwvE', 'title' => 'Rap do Jiren (Dragon Ball Super) | Tauz RapTributo 13'],
	['artista' => 'PlayerTauz', 'id' => 'gLg0frbz_h4', 'title' => 'Rap do Freeza (Dragon Ball Super) | Tauz RapTributo 15'],
	['artista' => 'PlayerTauz', 'id' => 'xk5y5JAwtI4', 'title' => 'Rap do God Of War | Tauz RapGame 01'],
	['artista' => 'PlayerTauz', 'id' => 'whWAw3kZonM', 'title' => 'Rap do Boruto | Tauz RapTributo 17'],
	['artista' => 'PlayerTauz', 'id' => 'uv4scCjW_k4', 'title' => 'Rap do Broly (Dragon Ball Super) | Tauz RapTributo 21'],
	['artista' => 'PlayerTauz', 'id' => 'drqwogSEgTo', 'title' => 'Rap do Goku Black (Dragon Ball Super) | Tauz RapTributo 71'],
	['artista' => 'PlayerTauz', 'id' => 'mpw4BE-y69E', 'title' => 'Rap do Orochimaru (Naruto) | Tauz RapTributo 66'],
	['artista' => 'PlayerTauz', 'id' => 'vgOdwnGQViE', 'title' => 'Rap do Neji (Naruto) | Tauz RapTributo 65'],
	['artista' => 'PlayerTauz', 'id' => 'UDXZVYX5FNA', 'title' => 'Rap do Bills (Dragon Ball Super) | Tauz RapTributo 60'],
	['artista' => 'PlayerTauz', 'id' => 'StPJhWmfzjU', 'title' => 'Rap do Jiraiya (Naruto) | Tauz RapTributo 48'],
	['artista' => 'PlayerTauz', 'id' => 'bNCoRi9ywd0', 'title' => 'Rap do Freeza (Dragon Ball Z) | Tauz RapTributo 41'],
	['artista' => 'PlayerTauz', 'id' => '1RwbaLQM3F8', 'title' => 'Rap do Broly (Dragon Ball Z) | Tauz RapTributo 51'],
	['artista' => 'PlayerTauz', 'id' => 'NMnN1_rS-iE', 'title' => 'Rap do Majin Boo (Dragon Ball Z) | Tauz RapTributo 36'],
	['artista' => 'PlayerTauz', 'id' => 'yPIzf1-iwnc', 'title' => 'Rap do Sub-Zero (Mortal Kombat) (Áudio) | Tauz RapTributo 34'],
	['artista' => 'PlayerTauz', 'id' => 'OCpYPR0vcrg', 'title' => 'Rap do Kenshi (Mortal Kombat) | Tauz RapTributo 33'],
	['artista' => 'PlayerTauz', 'id' => 'Ou4OY7fjcDM', 'title' => 'Rap do Ryu (Street Fighter) | Tauz RapTributo 32'],
	['artista' => 'PlayerTauz', 'id' => 'WDOKdBXIDTo', 'title' => 'Rap do Akuma (Street Fighter) | Tauz RapTributo 30'],
	['artista' => 'PlayerTauz', 'id' => 'WsEZOdYZaZk', 'title' => 'Rap do Ken (Street Fighter) | Tauz RapTributo 29'],
	['artista' => 'PlayerTauz', 'id' => 'A7dXwu1WepM', 'title' => 'Rap do L (Death Note) | Tauz RapTributo 28'],
	['artista' => 'PlayerTauz', 'id' => 'IfXZWup8LMs', 'title' => 'Rap do Nagato / Pain (Naruto) | Tauz RapTributo 21'],
	['artista' => 'PlayerTauz', 'id' => '9hI3iWRWABA', 'title' => 'Rap do Itachi (Naruto) | Tauz RapTributo 18'],
	['artista' => 'PlayerTauz', 'id' => 'RCTkiQlxEwA', 'title' => 'Rap do Sasuke Pt I (Naruto) | Tauz RapTributo 06'],
	['artista' => 'PlayerTauz', 'id' => 'z9buv3U1l9U', 'title' => 'Rap do Sasuke Pt II (Naruto) | Tauz RapTributo 19'],
	['artista' => 'PlayerTauz', 'id' => 'HG_IL-eDrjo', 'title' => 'Rap do Naruto | Tauz RapTributo 05'],
	['artista' => 'PlayerTauz', 'id' => '5WUF6-ikBlM', 'title' => 'Rap do Kakashi (Naruto) | Tauz RapTributo 09'],
	['artista' => 'PlayerTauz', 'id' => 'wjX2N_I0D_s', 'title' => 'Rap do Coringa (Batman) | Tauz RapTributo 12'],
	['artista' => 'PlayerTauz', 'id' => 'DjR3TQ6ZiCo', 'title' => 'Rap do Batman | Tauz RapTributo 13'],
	['artista' => 'PlayerTauz', 'id' => '4spsHI0sglg', 'title' => 'Rap do Trunks (Dragon Ball Z) | Tauz RapTributo 14'],
	['artista' => 'PlayerTauz', 'id' => 'FCm88wOgw7s', 'title' => 'Rap do Goku (Dragon Ball Z) | Tauz RapTributo 02'],
	['artista' => 'PlayerTauz', 'id' => '1ANF5X1Szn4', 'title' => 'Rap do Mortal Kombat | Tauz RapGame 18'],
	['artista' => 'PlayerTauz', 'id' => 'vfUtTIVA2xA', 'title' => 'Rap do GTA 5 (História) | Tauz RapGame 09'],
	['artista' => 'PlayerTauz', 'id' => 'VOknHbTPQhc', 'title' => 'Rap do Vegeta (Dragon Ball Z) | Tauz RapTributo 01'],
	['artista' => 'PlayerTauz', 'id' => 'dfWfIKkmcmo', 'title' => 'Rap do God of War | Tauz RapGame 12'],
	['artista' => 'PlayerTauz', 'id' => 'HG_IL-eDrjo', 'title' => 'Rap do Naruto | Tauz RapTributo 05'],
	['artista' => 'PlayerTauz', 'id' => 'U2Inn_QfPDg', 'title' => 'Rap do Obito (Naruto) | Tauz RapTributo 38'],


	['artista' => 'Tauz', 'id' => 'wqStK0uOYRk', 'title' => 'TAUZ - MINECRAFT | 01/31 | DROP NOSTALGICZ'],
	['artista' => 'Tauz', 'id' => 'DLu27xwy5Jg', 'title' => 'TAUZ - VEGETA | 02/31 | DROP NOSTALGICZ'],
	['artista' => 'Tauz', 'id' => '35JWZa3TZI8', 'title' => 'TAUZ - TRUNKS | 03/31 | DROP NOSTALGICZ'],
	['artista' => 'Tauz', 'id' => '1xCKYsRVuqk', 'title' => 'TAUZ - GOHAN | 04/31 | DROP NOSTALGICZ'],
	['artista' => 'Tauz', 'id' => 'zKDtB86Y-rk', 'title' => 'TAUZ - FREEZA | 05/31 | DROP NOSTALGICZ'],
	['artista' => 'Tauz', 'id' => 'acU21YQaT4g', 'title' => 'TAUZ - GOKU BLACK | 06/31 | DROP NOSTALGICZ'],
	['artista' => 'Tauz', 'id' => 'Blg7pL_Wum0', 'title' => 'TAUZ - BROLY | 07/31 | DROP NOSTALGICZ'],
	['artista' => 'Tauz', 'id' => 'yGUK2C1NW1w', 'title' => 'TAUZ - BARDOCK | 08/31 | DROP NOSTALGICZ'],
	['artista' => 'Tauz', 'id' => '9CKkCXWlcb8', 'title' => 'TAUZ - GOKU | 09/31 | DROP NOSTALGICZ'],
	['artista' => 'Tauz', 'id' => 'NhPsPAtU8yo', 'title' => 'TAUZ - SEIYA | 10/31 | DROP NOSTALGICZ'],
	['artista' => 'Tauz', 'id' => 'AH_O9Axewyk', 'title' => 'TAUZ - IKKI | 11/31 | DROP NOSTALGICZ'],
	['artista' => 'Tauz', 'id' => 'E1EnSR8OBIo', 'title' => 'TAUZ - NEJI | 12/31 | DROP NOSTALGICZ'],
	['artista' => 'Tauz', 'id' => 'AaOfJq_r77Q', 'title' => 'TAUZ - NAGATO | 13/31 | DROP NOSTALGICZ'],
	['artista' => 'Tauz', 'id' => 'D4J8kJoS9lA', 'title' => 'TAUZ - GAARA | 14/31 | DROP NOSTALGICZ'],
	['artista' => 'Tauz', 'id' => 'gbS7o0F8eNs', 'title' => 'TAUZ - MADARA | 15/31 | DROP NOSTALGICZ'],
	['artista' => 'Tauz', 'id' => 'YlITcuB_C8w', 'title' => 'TAUZ - NARUTO | 16/31 | DROP NOSTALGICZ'],
	['artista' => 'Tauz', 'id' => '0sfXhW1AraE', 'title' => 'TAUZ - ITACHI | 17/31 | DROP NOSTALGICZ'],
	['artista' => 'Tauz', 'id' => 'jtgIXsKpMck', 'title' => 'TAUZ - KAKASHI | 18/31 | DROP NOSTALGICZ'],
	['artista' => 'Tauz', 'id' => 'lzgzUHC72v8', 'title' => 'TAUZ - JIRAIYA | 19/31 | DROP NOSTALGICZ'],
	['artista' => 'Tauz', 'id' => '0FEb-DGOuC0', 'title' => 'TAUZ - ROCK LEE | 20/31 | DROP NOSTALGICZ'],
	['artista' => 'Tauz', 'id' => '8eAYfCEZKwQ', 'title' => 'TAUZ - SASUKE | 21/31 | DROP NOSTALGICZ'],
	['artista' => 'Tauz', 'id' => 'R4VJfkLIhtA', 'title' => 'TAUZ - MINATO | 22/31 | DROP NOSTALGICZ'],
	['artista' => 'Tauz', 'id' => 'clzpXFf_f80', 'title' => 'TAUZ - SHISUI | 23/31 | DROP NOSTALGICZ'],
	['artista' => 'Tauz', 'id' => 'pm5AFpPDJjg', 'title' => 'TAUZ - HASHIRAMA | 24/31 | DROP NOSTALGICZ'],
	['artista' => 'Tauz', 'id' => '29ZZs-RBd9g', 'title' => 'TAUZ - OBITO | 25/31 | DROP NOSTALGICZ'],
	['artista' => 'Tauz', 'id' => 'i4BgprQ2A5Y', 'title' => 'TAUZ - OROCHIMARU | 26/31 | DROP NOSTALGICZ'],
	['artista' => 'Tauz', 'id' => '5Rjtr0Rnu3o', 'title' => 'TAUZ - BILLS | 27/31 | DROP NOSTALGICZ'],
	['artista' => 'Tauz', 'id' => '-cm7aabV3ts', 'title' => 'TAUZ - ZORO | 28/31 | DROP NOSTALGICZ'],
	['artista' => 'Tauz', 'id' => 'vlXrovPLjBI', 'title' => 'TAUZ - BARBA BRANCA | 29/31 | DROP NOSTALGICZ'],
	['artista' => 'Tauz', 'id' => 'JsKSmUnKXuo', 'title' => 'TAUZ - MAJIN BOO | 30/31 | DROP NOSTALGICZ'],
	['artista' => 'Tauz', 'id' => 'RvFfdgcbZ-g', 'title' => 'TAUZ - MONSTER | 31/31 | DROP NOSTALGICZ'],
	// ['artista' => 'Tauz', 'id' => '','title' => ''],
	// ['artista' => 'Tauz', 'id' => '','title' => ''],
	// ['artista' => 'Tauz', 'id' => '','title' => ''],
	// ['artista' => 'Tauz', 'id' => '','title' => ''],


	['artista' => 'PlayerTauz', 'id' => 'MaN8bwp3dXA', 'title' => 'Chaves | Tauz RapTributo 16'],
	['artista' => 'PlayerTauz', 'id' => 'zy9-7EHScPg', 'title' => 'Homenagem Chapecoense #FORÇACHAPE'],
	['artista' => 'PlayerTauz', 'id' => 'taDkPtya428', 'title' => 'Anderson Silva | Tauz RapTributo 23'],

	['artista' => 'PlayerTauz', 'id' => '6U3MnqZ_TCQ', 'title' => 'Itachi'],
	['artista' => 'PlayerTauz', 'id' => 'n0q6yOHO-Ow', 'title' => 'TAKA'],
	['artista' => 'PlayerTauz', 'id' => '0OcN30pHXs8', 'title' => 'MADARA'],

	//Kanhanga
	['artista' => 'Kanhanga', 'id' => 'eCkFmY9Z1d8', 'title' => 'RAP DO ROGÉRIO CENI | RAP TRIBUTO 01| KANHANGA SPORTRAP | SÃO PAULO'],
	['artista' => 'Kanhanga', 'id' => 'KRN9eMeowkE', 'title' => 'RAP DO RONALDO "O FENÔMENO" | RAP TRIBUTO 02 | KANHANGA SPORTRAP'],
	['artista' => 'Kanhanga', 'id' => 'B3p4-cQ68v4', 'title' => 'GABRIEL JESUS | RAP TRIBUTO 05 | KANHANGA SPORTRAP'],
	['artista' => 'Kanhanga', 'id' => 'zqFTxDSiS2A', 'title' => 'RAP DO PAULO HENRIQUE "GANSO" | RAP TRIBUTO 06 | KANHANGA SPORTRAP | SEVILLA'],
	['artista' => 'Kanhanga', 'id' => '5n57-GVwFU8', 'title' => 'RAP DO ZÉ ROBERTO | TRIBUTO 10 | PALMEIRAS | KANHANGA SPORTRAP'],
	['artista' => 'Kanhanga', 'id' => 'muPbvBDvmPw', 'title' => 'RAP DO FALCÃO 12 | RAP TRIBUTO 13º | FUTSAL | KANHANGA SPORTRAP'],
	['artista' => 'Kanhanga', 'id' => 'oZ5BtAQr8D0', 'title' => 'PHILIPPE COUTINHO | RAP TRIBUTO 14º | LIVERPOOL | KANHANGA SPORTRAP'],
	['artista' => 'Kanhanga', 'id' => 'fAcdFKXJPn8', 'title' => 'RONALDINHO GAÚCHO | HOMENAGEM | RAP TRIBUTO 15º | KANHANGA SPORTRAP'],
	['artista' => 'Kanhanga', 'id' => 'UXiRwATQFeg', 'title' => 'JOSÉ ALDO | O CAMPEÃO VOLTOU | RAP TRIBUTO 16 | KANHANGA SPORTRAP | UFC, MMA'],
	['artista' => 'Kanhanga', 'id' => '5JVJnkXygyE', 'title' => 'RAP DO IBRAHIMOVÍC | RAP TRIBUTO 17º | KANHANGA SPORTRAP | MANCHESTER UNITED'],
	['artista' => 'Kanhanga', 'id' => 'aKR_0QL5ofY', 'title' => 'RAP DO ROBINHO | RAP TRIBUTO 18º | KANHANGA SPORTRAP'],
	['artista' => 'Kanhanga', 'id' => 'TA4pVqlBQ1Y', 'title' => 'RAP DO USAIN BOLT | RAP TRIBUTO 19º | KANHANGA SPORTRAP | ATLETISMO | JAMAICA |'],
	['artista' => 'Kanhanga', 'id' => 'ErV6Sb6kdlU', 'title' => 'RAP DO ADRIANO "IMPERADOR" | TRIBUTO 20º | KANHANGA SPORTRAP'],
	['artista' => 'Kanhanga', 'id' => 'mnY87u_Lv-I', 'title' => 'RAP DO MICHAEL JORDAN FT. TAUZ | RAP SPORT 21º | KANHANGA'],
	['artista' => 'Kanhanga', 'id' => 'rIWxUs89348', 'title' => 'CHAPECOENSE | TRAGÉDIA | HOMENAGEM | TRIBUTO 22º | KANHANGA SPORT RAP | PROD. ALIX GEORGE'],
	['artista' => 'Kanhanga', 'id' => '0YgiuhHGaN8', 'title' => 'RAP DO LUIS SUÁREZ | TRIBUTO 23º | KANHANGA SPORTRAP | BARCELONA'],
	['artista' => 'Kanhanga', 'id' => 'LbeY5tLERm4', 'title' => 'RAP DO GABRIEL MEDINA | SURF | CAMPEÃO MUNDIAL | KANHANGA SPORTRAP'],
	['artista' => 'Kanhanga', 'id' => 'LCtkyz_uGRk', 'title' => 'BENZEMA | RAP SPORT 25º | KANHANGA SPORTRAP'],
	['artista' => 'Kanhanga', 'id' => 'fbWVB-DlPp0', 'title' => 'KUN AGUERO | RAP SPORT 28º | KANHANGA'],
	['artista' => 'Kanhanga', 'id' => '1R4n10tS6lM', 'title' => 'MARTA | 6X BOLA DE OURO | RAP SPORT 29º | KANHANGA'],
	['artista' => 'Kanhanga', 'id' => 'l0joWC9XbC0', 'title' => 'RAP DO MICHAEL PHELPS | TRIBUTO 31º | NATAÇÃO | OLÍMPICO | KANHANGA SPORTRAP | PROD. BY VALENTINE'],
	['artista' => 'Kanhanga', 'id' => '_Fz5ktEVITY', 'title' => 'RAP DO MARCO REUS | WOODINHO | BORUSSIA DORTMUND | TRIBUTO 32º | KANHANGA SPORTRAP'],
	['artista' => 'Kanhanga', 'id' => 'mLkaWcH4W3o', 'title' => 'RAP DO BUFFON |JUVENTUS | ITÁLIA | TRIBUTO 34º | KANHANGA SPORTRAP (Produced by Didek & Veysigz)'],
	['artista' => 'Kanhanga', 'id' => 'gHQ8OS_tMzU', 'title' => 'RAP DO GRIEZMANN | ATLETICO DE MADRID | TRIBUTO 37º | KANHANGA SPORTRAP'],
	['artista' => 'Kanhanga', 'id' => 'pWDjR9W-e1I', 'title' => 'RAP DO DI MARIA | PARIS SAINT GERMAIN | TRIBUTO 39º | KANHANGA SPORTRAP'],
	['artista' => 'Kanhanga', 'id' => '7wO35esuZqc', 'title' => 'RAP DO SÉRGIO RAMOS | RAP SPORT 40º | KANHANGA'],
	['artista' => 'Kanhanga', 'id' => 'zCuW4pCkYgs', 'title' => 'Rap dos jogadores africanos | SportRap 138º | Kanhanga'],
	['artista' => 'Kanhanga', 'id' => 'ptNeE-HcDiA', 'title' => 'RAP DO ZIDANE | SPORTRAP 137º | KANHANGA'],
	['artista' => 'Kanhanga', 'id' => 'l1ObQ0I_8oo', 'title' => 'RAP DO PHILIPPE COUTINHO | RAP SPORT 120º | KANHANGA | PROD. EVANIR BEATS'],
	['artista' => 'Kanhanga', 'id' => 'TCtpMWcuXl8', 'title' => 'RAP DO FIRMINO | SPORTRAP 114º | KANHANGA'],
	['artista' => 'Kanhanga', 'id' => 'O3zy_mync84', 'title' => 'ANDRÉS INIESTA | BARCELONA | RAP TRIBUTO 102 º| FEAT. SRTA. PAOLA| ESPANHA | KANHANGA SPORTRAP'],
	['artista' => 'Kanhanga', 'id' => 'ozOIwZnogGg', 'title' => 'RAP DO THIAGO SILVA | SPORTRAP | 99º | KANHANGA'],
	['artista' => 'Kanhanga', 'id' => '9hSoTg2Rc68', 'title' => 'SELEÇÃO BRASILEIRA | RAP SPORT | KANHANGA'],
	['artista' => 'Kanhanga', 'id' => 'UAt7QhJQs8Q', 'title' => 'RAP DO BALE | REAL MADRID | TRIBUTO 83º | KANHANGA SPORTRAP'],
	['artista' => 'Kanhanga', 'id' => 'MoBQarc1JhU', 'title' => 'RAP DO KAKÁ | HOMENAGEM | DESPEDIDA | TRIBUTO 77º | KANHANGA SPORTRAP'],
	['artista' => 'Kanhanga', 'id' => '_zLup9oElvo', 'title' => 'RAP DO CASEMIRO | REAL MADRID | CASEMITO | TRIBUTO 74º | KANHANGA SPORTRAP'],
	['artista' => 'Kanhanga', 'id' => 'QVVcod8_Ccc', 'title' => 'MESSI |RAP SPORT 69º | KANHANGA'],
	['artista' => 'Kanhanga', 'id' => 'RRcCoTXmDvQ', 'title' => 'PAUL POGBA | RAP SPORT | KANHANGA SPORTRAP'],
	['artista' => 'Kanhanga', 'id' => 'oegGQPcdFR4', 'title' => 'LEBRON JAMES | RAP SPORT 60º | KANHANGA | PROD.: NEPUL BEATS'],
	['artista' => 'Kanhanga', 'id' => 'cExc6eVA68Y', 'title' => 'RAP DO DANIEL ALVES | MOTIVACIONAL | TRIBUTO 58º | KANHANGA SPORTRAP'],
	['artista' => 'Kanhanga', 'id' => 'Qrh4USZRoPA', 'title' => 'RAP DO CRISTIANO RONALDO | MOTIVACIONAL | KANHANGA'],
	['artista' => 'Kanhanga', 'id' => 'DJl9fIbaH1w', 'title' => 'RAP DO FRANCESCO TOTTI | ROMA | ITÁLIA | DESPEDIDA | TRIBUTO 51º | KANHANGA SPORTRAP'],
	['artista' => 'Kanhanga', 'id' => '8zb2Kca4OCo', 'title' => 'RAP DO MARCELO | REAL MADRID | SELEÇÃO BRASILEIRA | TRIBUTO 47º | KANHANGA SPORTRAP'],
	['artista' => 'Kanhanga', 'id' => '0rgR2wR0YJU', 'title' => 'RAP DO DYBALA | JUVENTUS | TRIBUTO 46º | KANHANGA SPORTRAP'],
	// ['artista' => 'Kanhanga', 'id' => '','title' => ''],
	// ['artista' => 'Kanhanga', 'id' => '','title' => ''],
	// ['artista' => 'Kanhanga', 'id' => '','title' => ''],



	//kanhanga & tauz
	['artista' => 'Tauz & Kanhanga', 'id' => 'wa3kNVk_8Xs', 'title' => 'Rap do Gareth Bale Ft. Kanhanga | Tauz RapSports 01'],
	['artista' => 'Tauz & Kanhanga', 'id' => '47wN-LciU2o', 'title' => 'Rap do Neymar Ft. Kanhanga | Tauz RapSports 02'],
	['artista' => 'Tauz & Kanhanga', 'id' => 'DZdwaAjqdnI', 'title' => 'Rap da Copa do Mundo Ft Kanhanga | Tauz RapSports 03'],
	['artista' => 'Tauz & Kanhanga', 'id' => 'CeQ1T_bwcBs', 'title' => 'Rap do Cristiano Ronaldo (Juventus) Ft. Kanhanga | Tauz RapSports 04'],
	['artista' => 'Tauz & Kanhanga', 'id' => 'tgsjfUWPgX4', 'title' => 'Rap do Messi Ft. Kanhanga | Tauz RapSports 05'],
	['artista' => 'Tauz & Kanhanga', 'id' => 'yQ6ih58XXEE', 'title' => 'TRAP do Neymar Ft. Kanhanga | Tauz RapSports 07'],
	['artista' => 'Tauz & Kanhanga', 'id' => 'SOdR5rI4-2Y', 'title' => 'TRAP do CR7 Ft. Kanhanga | Tauz RapSports 08'],
	['artista' => 'Tauz & Kanhanga', 'id' => 'GJkh5IWfD3U', 'title' => 'RAP DO MESSI - FEAT. TAUZ | TRIBUTO 11 | KANHANGA'],
	['artista' => 'Tauz & Kanhanga', 'id' => 'F65DtRNQG2o', 'title' => 'RAP DO NEYMAR | RAP SPORT 38º | TAUZ E KANHANGA'],
	// ['artista' => 'Tauz & Kanhanga', 'id' => '','title' => ''],
	// ['artista' => 'Tauz & Kanhanga', 'id' => '','title' => ''],
	// ['artista' => 'Tauz & Kanhanga', 'id' => '','title' => ''],

	//Flick
	['artista' => 'Flick Mc', 'id' => '74pE3QsFR-A', 'title' => 'Dragon Ball Z Rap [Saga Majin Boo]'],
	['artista' => 'Flick Mc', 'id' => 'GtW6Ns-qNY8', 'title' => 'Dragon Ball Z Rap [Saga Cell]'],
	['artista' => 'Flick Mc', 'id' => 'BD_QxJ4wkl0', 'title' => 'Dragon Ball Z Rap [Saga Freeza]'],
	['artista' => 'Flick Mc', 'id' => 'CA3nvkqtikI', 'title' => 'Dragon Ball Z Rap [Saga Saiyajins]'],
	['artista' => 'Flick Mc', 'id' => '5Ka9BUL4eGk', 'title' => 'Rap da História do Goku'],
	['artista' => 'Flick Mc', 'id' => '6VUl9Vn8rHU', 'title' => 'RAP da História do Vegeta'],


	//7 Minutoz
	['artista' => '7 Minutoz', 'id' => 'mKvpHbF7Cvs', 'title' => 'Rap do Goku (Dragon Ball Z)'],
	['artista' => '7 Minutoz', 'id' => 'CvfNBZ3Sdvw', 'title' => 'Rap do Dragon Ball Z: Guerreiro Saiyajin'],
	// ['artista' => '7 Minutoz', 'id' => '','title' => ''],
	// ['artista' => '7 Minutoz', 'id' => '','title' => ''],

	//Bob Marley
	['artista' => 'Bob Marley', 'id' => 'NOyRsPDPfMM', 'title' => 'Three Little Birds'],

];
